version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tcrone@newrelic.com
      PGADMIN_DEFAULT_PASSWORD: drowsap
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin

volumes:
  postgres_data:
  pgadmin_data: